apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: environment-template
  title: Environment Request Template
  description: Request the Creation of an environment 
  tags:
    - recommended
    - environment
    - provisioning
spec:
  owner: service@example.com
  type: service

  parameters:
    - title: Environment Request
      required:
        - applicationId
        - owner
        - environment
        - cluster
        - size
        - description
      properties:
        applicationId:
          title: Application Id
          type: string
          description: Application Id which will use this environment
        environment:
          title: Environment
          type: string
          enum: ["dev", "test", "prod"]
          description: Purpose for this environment
        description:
          title: Description
          type: string
          description: Short description for this environment
        cluster:
          title: Cluster
          type: string
          description: Cluster in which the namespace for this environment will be created
          enum: ["non-prod", "prod"]
        size:
          title: Size
          type: string
          description: Size of the namespace in terms of resources available
          enum: ["small", "medium", "large"]
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: 
              - Group

      dependencies:
        size:
          allOf:
            - if:
                properties:
                  size:
                    const: "small"
              then:
                properties:
                  limitsMemory:
                    type: string
                    default: "4Gi"
                  requestsCpu:
                    type: string
                    default: "2"
                  requestsMemory:
                    type: string
                    default: "4Gi"
                  persistentvolumeclaims:
                    type: string
                    default: "5"
                  requestsStorage:
                    type: string
                    default: "50Gi"
              else:
                properties:
                  limitsMemory:
                    type: string
                    default: "8Gi"
                  requestsCpu:
                    type: string
                    default: "4"
                  requestsMemory:
                    type: string
                    default: "8Gi"
                  persistentvolumeclaims:
                    type: string
                    default: "10"
                  requestsStorage:
                    type: string
                    default: "100Gi"

  steps:
    - id: template
      name: Code Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender: []
        values:
          description: ${{ parameters.description }}
          cluster: ${{ parameters.cluster }}
          environment: ${{ parameters.environment }}
          owner: ${{ parameters.owner.split("/")[1] }}
          applicationId: ${{ parameters.applicationId }}
          size: ${{parameters.size}}
          limitsMemory: ${{parameters.limitsMemory}}
    - id: pull-request
      name: make a pr with the new namespace
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=boot-project-values&owner=eformat
        branchName: ${{ parameters.applicationId }}-${{ parameters.environment }}
        title: clusters/${{ parameters.cluster }}/${{ parameters.applicationId }}-${{ parameters.environment }} namespace
        description: This is a request for the creation of the ${{ parameters.applicationId }}-${{ parameters.environment }} namespace in the ${{ parameters.cluster }} from the ${{ parameters.owner }} team
