apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: environment-template
  title: Environment Request Template
  description: Request the Creation of an environment 
  tags:
    - recommended
    - environment
    - provisioning
spec:
  owner: service@example.com
  type: service

  parameters:
    - title: Environment Request
      required:
        - applicationId
        - owner
        - environment
        - cluster
        - size
        - description
      properties:
        applicationId:
          title: Application Id
          type: string
          description: Application Id which will use this environment
        environment:
          title: Environment
          type: string
          description: Purpose for this environment
          enum: ["dev", "test", "prod"]
          ui:widget: radio
        description:
          title: Description
          type: string
          description: Short description for this environment
        cluster:
          title: Cluster
          type: string
          description: Cluster in which the namespace for this environment will be created
          enum: ["non-prod", "prod"]
          ui:widget: radio
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: 
              - Group
        size:
          title: Size
          type: string
          description: Size of the namespace in terms of resources available
          enum: ["small", "medium", "large", "custom"]
          ui:widget: radio

      dependencies:
        size:
          oneOf:
            - properties:
                size:
                  enum:
                    - small
                limitsMemory:
                  title: Memory
                  type: string
                  default: "4Gi"
                  ui:readonly: true
                requestsCpu:
                  type: string
                  default: "2"
                  ui:readonly: true
                requestsMemory:
                  type: string
                  default: "4Gi"
                  ui:readonly: true
                persistentVolumeClaims:
                  type: string
                  default: "5"
                  ui:readonly: true
                requestsStorage:
                  type: string
                  default: "50Gi"
                  ui:readonly: true
            - properties:
                size:
                  enum:
                    - medium
                limitsMemory:
                  title: Memory
                  type: string
                  default: "8Gi"
                  ui:readonly: true
                requestsCpu:
                  type: string
                  default: "4"
                  ui:readonly: true
                requestsMemory:
                  type: string
                  default: "8Gi"
                  ui:readonly: true
                persistentVolumeClaims:
                  type: string
                  default: "10"
                  ui:readonly: true
                requestsStorage:
                  type: string
                  default: "100Gi"
                  ui:readonly: true
            - properties:
                size:
                  enum:
                    - large
                limitsMemory:
                  title: Memory
                  type: string
                  default: "16Gi"
                  ui:readonly: true
                requestsCpu:
                  type: string
                  default: "12"
                  ui:readonly: true
                requestsMemory:
                  type: string
                  default: "16Gi"
                  ui:readonly: true
                persistentVolumeClaims:
                  type: string
                  default: "20"
                  ui:readonly: true
                requestsStorage:
                  type: string
                  default: "1000Gi"
                  ui:readonly: true
            - properties:
                size:
                  enum:
                    - custom
                limitsMemory:
                  title: Memory
                  type: string
                  default: "1Gi"
                  ui:readonly: false
                requestsCpu:
                  type: string
                  default: "2"
                  ui:readonly: false
                requestsMemory:
                  type: string
                  default: "4Gi"
                  ui:readonly: false
                persistentVolumeClaims:
                  type: string
                  default: "5"
                  ui:readonly: false
                requestsStorage:
                  type: string
                  default: "20Gi"
                  ui:readonly: false
  steps:
    - id: template
      name: Code Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender: []
        values:
          description: ${{ parameters.description }}
          cluster: ${{ parameters.cluster }}
          environment: ${{ parameters.environment }}
          owner: ${{ parameters.owner.split("/")[1] }}
          applicationId: ${{ parameters.applicationId }}
          size: ${{parameters.size}}
          limitsMemory: ${{parameters.limitsMemory}}
          requestsCpu: ${{values.requestsCPU}}
          requestsMemory: ${{values.requestsMemory}}
          persistentVolumeClaims: ${{values.persistentVolumeClaims}}
          requestsStorage: ${{values.requestsStorage}}
    - id: pull-request
      name: make a pr with the new namespace
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=boot-project-values&owner=eformat
        branchName: ${{ parameters.applicationId }}-${{ parameters.environment }}
        title: clusters/${{ parameters.cluster }}/${{ parameters.applicationId }}-${{ parameters.environment }} namespace
        description: This is a request for the creation of the ${{ parameters.applicationId }}-${{ parameters.environment }} namespace in the ${{ parameters.cluster }} from the ${{ parameters.owner }} team
